server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
          
  # NGINX access logs
  - job_name: nginx_access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          log_type: access
          __path__: /var/log/nginx/access.log
          
  # NGINX error logs
  - job_name: nginx_error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          log_type: error
          __path__: /var/log/nginx/error.log

  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # Application specific logs
  - job_name: haroonnet_api
    static_configs:
      - targets:
          - localhost
        labels:
          job: haroonnet
          service: api
          __path__: /var/log/haroonnet/api.log
          
  - job_name: haroonnet_worker
    static_configs:
      - targets:
          - localhost
        labels:
          job: haroonnet
          service: worker
          __path__: /var/log/haroonnet/worker.log

  # FreeRADIUS logs
  - job_name: freeradius
    static_configs:
      - targets:
          - localhost
        labels:
          job: freeradius
          __path__: /var/log/freeradius/radius.log